trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    git config --global user.email "sergiu.bucur@outlook.com"
    git config --global user.name "Sergiu Bucur"
    npm install
    npm run deploy
  displayName: 'npm install, build and deploy'
