enum Types {
	ILogger = 1,
	IAssetService,
	IInputTracker,
	ICore,
	ICamera,
	IRenderer,
	IWorldMeshBuilder,
	IMapLoader,
	IWorld,
	IMouseControls,
	IPlayer,
	IMonster,
	IEntityId,
	IEntityMovementEngine,
	IUIRoot,
	IProjectile,
	IPointLightCache,
	IEntityMeleeAttackEngine,
	IPrimitiveCache,
	IEntityDeathAnimationEngine,
	IEntityRangedAttackEngine,
	IDoor,
	IPlayerSpellEngine,
	IFpsDisplay,
	ITooltipService,
	IPlayerUseEngine,
	IPowerup,
	IPlayerAuraEngine,
	ILoadingDisplay
};

export default Types;
